name = "n8nworkflows"
compatibility_date = "2026-01-11"
main = "index.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
PUBLIC_SITE_URL = "https://n8nworkflow.com"
