name = "n8nworkflows"
compatibility_date = "2026-01-11"
compatibility_flags = [ "nodejs_compat" ]
main = "./dist/_worker.js/index.js"

[assets]
directory = "./dist"
exclude = ["data/workflows/**/*"]

[[kv_namespaces]]
binding = "SESSION"
id = "local_session_kv"

[vars]
PUBLIC_SITE_URL = "https://n8nworkflow.com"
